### ISSUE TITLE
rqt_bag import error

### ISSUE THREAD

**Issue by sofiamgsfernandes** [socrob/autonomous_systems#17]
After updating and upgrading ubuntu 16.04 I am not able to access `rqt_bag,` although I can still open rqt. I have no idea how to solve this situation.

```
sofia@sofia-X541UJ:~ $ rqt_bag
Traceback (most recent call last):
  File "/opt/ros/kinetic/bin/rqt_bag", line 5, in <module>
    from rqt_bag.bag import Bag
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_bag/bag.py", line 39, in <module>
    from .bag_widget import BagWidget
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_bag/bag_widget.py", line 40, in <module>
    from python_qt_binding.QtCore import Qt, qInfo, qWarning, Signal
ImportError: cannot import name qInfo
```

**Comment by oscar-lima** [comment]
Hi Sofia! As a workaround please consider using rosbag from command line.

rosbag play —clock filename.bag
